name: Hprofile Actions
on: 
  workflow_dispatch

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Testing workflow
        run: echo "workflow works!"

      - name: Checkout
        uses: actions/checkout@v4 

      - name: mvn test
        run: mvn test
      
      - name: checkstyle
        run: mvn checkstyle:checkstyle